import { Link } from 'react-router-dom'
import { AlertTriangle, CheckCircle2, Clock3, Github, RefreshCcw, ShieldAlert } from 'lucide-react'
import { useApi } from '../lib/hooks'
import { post } from '../lib/api'
import { ErrorBox, Loading, PageHeader, Panel, RiskPill, StatusBadge } from '../components/UI'

export function Approvals(){const api=useApi<any[]>('/approvals',[]);if(api.loading)return <Loading/>;if(api.error)return <ErrorBox message={api.error}/>;return <><PageHeader eyebrow="Human control" title="Pending approvals" description="Reviewers decide what is published. AI and static findings remain internal until explicitly approved."/><Panel><div className="table-wrap"><table><thead><tr><th>Pull request</th><th>Repository</th><th>Risk</th><th>Findings</th><th>Reviewer</th><th>Status</th><th></th></tr></thead><tbody>{api.data.map(x=><tr key={x.id}><td><Link className="table-title" to={`/pull-requests/${x.pull_request_id}`}>#{x.pull_request_number} {x.pull_request_title}</Link><span className="muted">Review v{x.version}</span></td><td>{x.repository}</td><td><RiskPill score={x.risk_score} level={x.risk_level}/></td><td>{x.total_findings}<span className="muted">{x.high_critical} high/critical</span></td><td>{x.assigned_reviewer||'Unassigned'}</td><td><StatusBadge value={x.status}/></td><td><Link className="secondary-button compact" to={`/pull-requests/${x.pull_request_id}`}>Open workspace</Link></td></tr>)}</tbody></table></div></Panel></>}

export function ReviewHistory(){const prs=useApi<any[]>('/pull-requests',[]);if(prs.loading)return <Loading/>;return <><PageHeader eyebrow="Traceability" title="Review history" description="Preserve review versions, commit SHAs, resolutions, publication decisions, and re-analysis results."/><div className="history-list">{prs.data.map(pr=><HistoryRow pr={pr} key={pr.id}/>)}</div></>}
function HistoryRow({pr}:{pr:any}){const history=useApi<any[]>(`/pull-requests/${pr.id}/review-history`,[]);return <Panel title={`#${pr.github_number} ${pr.title}`} subtitle={pr.repository}>{history.loading?<div className="loading inline">Loading versions…</div>:<div className="table-wrap"><table><thead><tr><th>Version</th><th>Commit</th><th>Status</th><th>Risk</th><th>Findings</th><th>Published</th><th>Resolved</th></tr></thead><tbody>{history.data.map(x=><tr key={x.id}><td>v{x.version}</td><td><code>{x.commit_sha.slice(0,9)}</code></td><td><StatusBadge value={x.status}/></td><td>{x.risk_score}</td><td>{x.findings_count}</td><td>{x.published_findings}</td><td>{x.resolved_findings}</td></tr>)}</tbody></table></div>}</Panel>}

export function FailedJobs(){const api=useApi<any[]>('/failed-jobs',[]);async function retry(id:number){await post(`/failed-jobs/${id}/retry`);api.reload()}if(api.loading)return <Loading/>;return <><PageHeader eyebrow="Operations" title="Failed analysis and retry" description="Analyzer and integration failures remain visible, auditable, and independently retryable."/>{api.data.length===0?<Panel><div className="healthy-state"><CheckCircle2 size={42}/><strong>No failed analysis jobs</strong><span>All current jobs completed or are awaiting human review.</span></div></Panel>:api.data.map(x=><Panel key={x.id}><div className="failed-row"><AlertTriangle/><div><strong>{x.repository} PR #{x.pull_request_number}</strong><span>{x.failure_reason}</span></div><button className="primary-button" onClick={()=>retry(x.id)}><RefreshCcw/>Retry</button></div></Panel>)}</>}

export function GithubIntegration(){const api=useApi<any>('/integrations/github/status',{});if(api.loading)return <Loading/>;return <><PageHeader eyebrow="GitHub App" title="Integration status" description="Minimal-permission GitHub App authentication, signed webhooks, pull-request metadata, and controlled review publishing."/><div className="integration-hero"><Github size={58}/><div><h2>{api.data.demo_mode?'Demo integration active':api.data.configured?'GitHub App connected':'Configuration required'}</h2><p>{api.data.demo_mode?'Controlled sample repositories are connected. Live API calls are disabled until credentials are added.':'The platform will use installation tokens rather than personal access tokens.'}</p></div><StatusBadge value={api.data.demo_mode?'demo connected':api.data.configured?'active':'pending configuration'}/></div><div className="two-col"><Panel title="Installation and webhook"><dl className="metadata-list"><div><dt>Installation ID</dt><dd>{api.data.organization_installation_id||'Not configured'}</dd></div><div><dt>Webhook secret</dt><dd>{api.data.webhook_secret_configured?'Configured':'Use .env before production'}</dd></div><div><dt>Event endpoint</dt><dd><code>/api/webhooks/github</code></dd></div><div><dt>Signature algorithm</dt><dd>HMAC SHA-256</dd></div></dl></Panel><Panel title="Requested permissions" subtitle="Least-privilege GitHub App scope"><div className="permission-list">{(api.data.permissions||[]).map((x:string)=><div key={x}><ShieldAlert size={17}/><span>{x}</span><CheckCircle2 size={17}/></div>)}</div></Panel></div><Panel title="Live-mode setup"><ol className="setup-list"><li>Create a GitHub App and grant metadata read, contents read, pull requests write, and checks read.</li><li>Set the webhook URL to <code>https://your-domain/api/webhooks/github</code> and create a strong webhook secret.</li><li>Store the App ID, installation ID, private-key path, and webhook secret in the backend environment.</li><li>Disable <code>DEMO_MODE</code>, verify the installation, and test on controlled repositories before wider rollout.</li></ol></Panel></>}
