import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { AlertTriangle, Check, ChevronDown, Code2, FileCode2, GitCommit, GitPullRequest, Play, RefreshCcw, Send, Shield, TestTube2, X } from 'lucide-react'
import { useApi } from '../lib/hooks'
import { post } from '../lib/api'
import { Badge, ErrorBox, Loading, PageHeader, Panel, RiskGauge, RiskPill, SeverityBadge, StatusBadge } from '../components/UI'
import type { Finding, PullRequest } from '../lib/types'

export function PullRequestQueue(){const api=useApi<PullRequest[]>('/pull-requests',[]);const [risk,setRisk]=useState('');if(api.loading)return <Loading/>;if(api.error)return <ErrorBox message={api.error}/>;const rows=api.data.filter(x=>!risk||x.risk_level===risk);return <><PageHeader eyebrow="Review operations" title="Pull-request queue" description="Prioritize analysis and human review using risk, severity, repository policy, and workflow status."/><Panel><div className="toolbar"><select value={risk} onChange={e=>setRisk(e.target.value)}><option value="">All risk levels</option><option value="critical">Critical</option><option value="high">High</option><option value="moderate">Moderate</option><option value="low">Low</option></select><button className="secondary-button"><RefreshCcw size={16}/>Refresh</button></div><div className="table-wrap"><table><thead><tr><th>Pull request</th><th>Repository</th><th>Author</th><th>Change</th><th>Risk</th><th>Analysis</th><th>Review</th><th>Reviewer</th></tr></thead><tbody>{rows.map(pr=><tr key={pr.id}><td><Link className="table-title" to={`/pull-requests/${pr.id}`}>#{pr.github_number} {pr.title}</Link><span className="muted">{pr.base_branch} ← {pr.head_branch}</span></td><td>{pr.repository}<span className="muted">{pr.language}</span></td><td>{pr.author}</td><td>{pr.changed_files_count} files<span className="muted additions">+{pr.additions} <i>−{pr.deletions}</i></span></td><td><RiskPill score={pr.risk_score} level={pr.risk_level}/></td><td><StatusBadge value={pr.analysis_status}/></td><td><StatusBadge value={pr.review_status}/></td><td>{pr.assigned_reviewer||'Unassigned'}</td></tr>)}</tbody></table></div></Panel></>}

function FindingCard({finding,onDecision}:{finding:Finding,onDecision:(id:number,decision:string)=>void}){const [open,setOpen]=useState(false);return <div className={`finding-card ${finding.severity}`}><div className="finding-summary" onClick={()=>setOpen(!open)}><SeverityBadge value={finding.severity}/><div><strong>{finding.title}</strong><span><FileCode2 size={14}/>{finding.file_path}:{finding.start_line} · {finding.category} · {Math.round(finding.confidence*100)}% confidence</span></div><StatusBadge value={finding.status}/><ChevronDown className={open?'rotate':''}/></div>{open&&<div className="finding-detail"><div className="finding-text"><h4>Why it matters</h4><p>{finding.explanation}</p><h4>Evidence</h4><p>{finding.evidence}</p><h4>Suggested change</h4><p>{finding.suggested_fix}</p></div><pre className="code-snippet"><code>{finding.code_snippet||'No code excerpt stored for this finding.'}</code></pre><div className="finding-actions"><button className="approve-button" onClick={()=>onDecision(finding.id,'approve')}><Check size={16}/>Approve</button><button className="secondary-button" onClick={()=>onDecision(finding.id,'edit')}>Edit wording</button><button className="secondary-button" onClick={()=>onDecision(finding.id,'internal_note')}>Internal note</button><button className="danger-button" onClick={()=>onDecision(finding.id,'false_positive')}><X size={16}/>False positive</button></div></div>}</div>}

export function ReviewWorkspace(){const {id}=useParams();const api=useApi<any>(`/pull-requests/${id}`,{});const [tab,setTab]=useState('findings');const [busy,setBusy]=useState('');const [message,setMessage]=useState('');if(api.loading)return <Loading/>;if(api.error)return <ErrorBox message={api.error}/>;const pr=api.data;const review=pr.latest_review;async function decision(findingId:number,action:string){setBusy(String(findingId));try{await post(`/findings/${findingId}/decision`,{decision:action,comment:action==='false_positive'?'Reviewed and dismissed by human reviewer.':undefined,edited_content:action==='edit'?'Edited reviewer wording: '+review.findings.find((x:Finding)=>x.id===findingId).title:undefined});await api.reload()}finally{setBusy('')}}async function analyze(){setBusy('analysis');setMessage('');try{const r=await post<any>(`/pull-requests/${id}/analyze`,{trigger_event:'manual.reanalysis',force:true});setMessage(`Review run ${r.review_run_id} completed.`);await api.reload()}catch(e){setMessage(e instanceof Error?e.message:'Analysis failed')}finally{setBusy('')}}async function approveAll(){await post(`/review-runs/${review.id}/approve-all`);setMessage('All eligible findings approved for publication.');await api.reload()}async function publish(){const r=await post<any>(`/review-runs/${review.id}/publish`,{review_decision:'request_changes',include_summary:true,dry_run:true});setMessage(`GitHub review ${r.items[0].github_comment_id} published in demo mode.`);await api.reload()}
return <><PageHeader eyebrow={`${pr.repository.full_name} · Pull request #${pr.github_number}`} title={pr.title} description={`${pr.author} proposes ${pr.head_branch} into ${pr.base_branch} · ${pr.changed_files_count} files · +${pr.additions} −${pr.deletions}`} actions={<><button className="secondary-button" onClick={analyze} disabled={busy==='analysis'}><Play size={16}/>Re-analyze</button><button className="primary-button" onClick={publish}><Send size={16}/>Publish approved review</button></>}/>{message&&<div className="success-banner">{message}</div>}
<div className="review-hero"><Panel><div className="risk-overview"><RiskGauge score={review.risk_score}/><div><p className="eyebrow">Pull-request risk</p><h2>{pr.risk_level.toUpperCase()} RISK</h2><p>{review.merge_recommendation.replaceAll('_',' ')}</p><StatusBadge value={review.status}/></div></div></Panel><Panel title="Risk explanation" subtitle="Deterministic factors contributing to the score"><div className="factor-list">{review.risk_factors.map((x:any,i:number)=><div key={i}><span>{x.factor}</span><strong className={x.points<0?'negative':''}>{x.points>0?'+':''}{x.points}</strong></div>)}</div></Panel><Panel title="Analysis coverage" subtitle="Repository-aware sources"><div className="coverage-grid"><div><Shield/><strong>{review.findings.filter((x:Finding)=>x.category==='security').length}</strong><span>Security findings</span></div><div><Code2/><strong>{review.analyzer_runs.length}</strong><span>Analyzer runs</span></div><div><TestTube2/><strong>{review.test_recommendations.length}</strong><span>Test recommendations</span></div><div><GitCommit/><strong>v{review.version}</strong><span>Review version</span></div></div></Panel></div>
<div className="tabs"><button className={tab==='findings'?'active':''} onClick={()=>setTab('findings')}>Findings <em>{review.findings.length}</em></button><button className={tab==='diff'?'active':''} onClick={()=>setTab('diff')}>Changed files</button><button className={tab==='tests'?'active':''} onClick={()=>setTab('tests')}>Tests & docs</button><button className={tab==='analyzers'?'active':''} onClick={()=>setTab('analyzers')}>Analyzer runs</button></div>
{tab==='findings'&&<Panel title="Review findings" subtitle="Approve, edit, dismiss, suppress, or keep each finding internal" action={<button className="approve-button" onClick={approveAll}><Check size={16}/>Approve eligible findings</button>}><div className="finding-list">{review.findings.map((f:Finding)=><FindingCard finding={f} onDecision={decision} key={f.id}/>)}</div></Panel>}
{tab==='diff'&&<Panel title="Repository context and changed files" subtitle="Normalized change package used by analyzers and AI review"><div className="changed-file-list">{pr.changed_files.map((f:any)=><div key={f.filename}><FileCode2/><strong>{f.filename}</strong><span className="additions">+{f.additions}</span><span className="deletions">−{f.deletions}</span></div>)}</div><pre className="diff-view"><code>{pr.diff_text}</code></pre></Panel>}
{tab==='tests'&&<div className="two-col"><Panel title="Test recommendations">{review.test_recommendations.length?review.test_recommendations.map((x:any)=><div className="recommendation" key={x.id}><Badge tone={x.priority}>{x.priority}</Badge><div><strong>{x.test_type} · {x.target_module}</strong><p>{x.scenario}</p><span>Expected: {x.expected_result}</span></div></div>):<p>No additional tests recommended.</p>}</Panel><Panel title="Documentation recommendations">{review.documentation_recommendations.length?review.documentation_recommendations.map((x:any)=><div className="recommendation" key={x.id}><Badge tone={x.priority}>{x.priority}</Badge><div><strong>{x.document_type}</strong><p>{x.reason}</p><span>{x.suggested_update}</span></div></div>):<p>No documentation changes required.</p>}</Panel></div>}
{tab==='analyzers'&&<Panel title="Analyzer execution"><div className="table-wrap"><table><thead><tr><th>Tool</th><th>Version</th><th>Status</th><th>Duration</th><th>Normalized findings</th></tr></thead><tbody>{review.analyzer_runs.map((x:any)=><tr key={x.id}><td>{x.tool_name}</td><td>{x.tool_version}</td><td><StatusBadge value={x.status}/></td><td>{x.duration_ms} ms</td><td>{x.output.normalized_findings}</td></tr>)}</tbody></table></div></Panel>}</>}
