import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Boxes, Filter, Github, RefreshCcw, Save, Search, ShieldCheck } from 'lucide-react'
import { useApi } from '../lib/hooks'
import { put } from '../lib/api'
import { ErrorBox, Loading, PageHeader, Panel, RiskPill, StatusBadge } from '../components/UI'
import type { Repository } from '../lib/types'

export function RepositoryList() {
  const { data, loading, error } = useApi<Repository[]>('/repositories', [])
  const [query,setQuery]=useState('')
  if(loading) return <Loading/>; if(error) return <ErrorBox message={error}/>
  const rows=data.filter(r=>`${r.full_name} ${r.primary_language}`.toLowerCase().includes(query.toLowerCase()))
  return <><PageHeader eyebrow="Repository estate" title="Connected repositories" description="Manage GitHub connections, review profiles, analyzers, branches, and repository-level quality policy." actions={<button className="primary-button"><Github size={17}/>Connect repository</button>}/>
  <Panel><div className="toolbar"><div className="search-box"><Search size={17}/><input placeholder="Search repositories" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="secondary-button"><Filter size={16}/>Filters</button><button className="secondary-button"><RefreshCcw size={16}/>Sync all</button></div>
  <div className="table-wrap"><table><thead><tr><th>Repository</th><th>Language</th><th>Connection</th><th>Review profile</th><th>Open PRs</th><th>Avg risk</th><th>Last sync</th></tr></thead><tbody>{rows.map(repo=><tr key={repo.id}><td><Link to={`/repositories/${repo.id}`} className="repo-name"><Boxes size={18}/><div><strong>{repo.full_name}</strong><span>{repo.webhook_status} webhook</span></div></Link></td><td><span className="language-chip">{repo.primary_language}</span></td><td><StatusBadge value={repo.connection_status}/></td><td>{repo.active_review_profile.replaceAll('_',' ')}</td><td>{repo.open_pull_requests}</td><td><RiskPill score={Math.round(repo.average_risk)} level={repo.average_risk>=75?'critical':repo.average_risk>=50?'high':repo.average_risk>=25?'moderate':'low'}/></td><td>{repo.last_synchronized_at?new Date(repo.last_synchronized_at).toLocaleString():'—'}</td></tr>)}</tbody></table></div></Panel></>
}

export function RepositoryDetail() {
  const { id }=useParams(); const api=useApi<any>(`/repositories/${id}`,{}); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('')
  if(api.loading) return <Loading/>; if(api.error) return <ErrorBox message={api.error}/>
  const repo=api.data; const policy=repo.policy
  async function savePolicy(){setSaving(true);setMessage(''); try{const payload={...policy}; delete payload.id;delete payload.repository_id;await put(`/repositories/${id}/policy`,payload);setMessage('Repository policy saved.')}catch(e){setMessage(e instanceof Error?e.message:'Save failed')}finally{setSaving(false)}}
  return <><PageHeader eyebrow="Repository configuration" title={`${repo.owner}/${repo.name}`} description={`${repo.primary_language} · ${repo.visibility} repository · ${repo.active_review_profile.replaceAll('_',' ')}`} actions={<><StatusBadge value={repo.connection_status}/><button className="primary-button" onClick={savePolicy} disabled={saving}><Save size={17}/>{saving?'Saving…':'Save policy'}</button></>}/>
  {message&&<div className="success-banner">{message}</div>}
  <div className="detail-grid"><Panel title="GitHub connection" subtitle="Installation, webhook, and synchronization health"><div className="connection-card"><Github size={34}/><div><strong>GitHub App connected</strong><span>Installation ID {repo.github_repository_id || 'demo'} · webhook {repo.webhook_status}</span></div><StatusBadge value={repo.connection_status}/></div><dl className="metadata-list"><div><dt>Default branch</dt><dd>{repo.default_branch}</dd></div><div><dt>Primary language</dt><dd>{repo.primary_language}</dd></div><div><dt>Last synchronized</dt><dd>{repo.last_synchronized_at?new Date(repo.last_synchronized_at).toLocaleString():'—'}</dd></div></dl></Panel>
  <Panel title="Active review policy" subtitle="Human-controlled repository review behavior"><div className="form-grid"><label>Review profile<select defaultValue={policy.review_profile}><option value="standard_application">Standard Application</option><option value="security_sensitive_application">Security-Sensitive Application</option><option value="api_service">API Service</option><option value="data_ml_project">Data / ML Project</option><option value="laravel_application">Laravel Application</option></select></label><label>Minimum publish severity<select defaultValue={policy.minimum_severity}><option>info</option><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>Maximum diff size<input type="number" defaultValue={policy.maximum_diff_size}/></label></div><div className="toggle-list">{[['Security checks',policy.security_checks],['Test-gap review',policy.test_review],['Documentation review',policy.documentation_review],['Human approval required',policy.approval_required],['Re-review on push',policy.re_review_on_push]].map(([name,value])=><label key={String(name)}><span>{name}</span><input type="checkbox" defaultChecked={Boolean(value)}/><i/></label>)}</div></Panel>
  <Panel title="Monitored branches" subtitle="Pull requests targeting these branches are eligible"><div className="chip-list">{policy.monitored_branches.map((x:string)=><span key={x}>{x}</span>)}</div><h4>Ignored paths</h4><div className="chip-list muted-chips">{policy.ignored_paths.map((x:string)=><span key={x}>{x}</span>)}</div></Panel>
  <Panel title="Analyzer profile" subtitle="Language-aware deterministic tooling"><div className="analyzer-grid">{(repo.primary_language==='Python'?['Ruff','Bandit','mypy','pytest coverage']:repo.primary_language==='PHP'?['PHPStan','Laravel Pint','Composer Audit','PHPUnit']:repo.primary_language==='TypeScript'?['ESLint','TypeScript','npm audit','test coverage']:['Checkstyle','SpotBugs','PMD','Maven tests']).map(x=><div key={x}><ShieldCheck/><strong>{x}</strong><StatusBadge value="enabled"/></div>)}</div></Panel></div>
  <Panel title="Recent pull requests" subtitle="Latest review activity for this repository"><div className="table-wrap"><table><thead><tr><th>Pull request</th><th>Risk</th><th>Analysis</th><th>Review</th></tr></thead><tbody>{repo.pull_requests.map((pr:any)=><tr key={pr.id}><td><Link className="table-title" to={`/pull-requests/${pr.id}`}>#{pr.github_number} {pr.title}</Link></td><td><RiskPill score={pr.risk_score} level={pr.risk_level}/></td><td><StatusBadge value={pr.analysis_status}/></td><td><StatusBadge value={pr.review_status}/></td></tr>)}</tbody></table></div></Panel></>
}
